version: '3.7'
services:
  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "8083:80"
      - "443:443"
    networks:
      - was-net
    depends_on:
      - server

  server:
    image: jaeseo/fitapet:latest
    container_name: fitapet-api
    restart: unless-stopped
    expose:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    networks:
      - was-net

networks:
  was-net:
    name: was-net
    external: true
