version: '3.7'
services:
  nginx:
    image: jaeseo/nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  api:
    image: jaeseo/fitapet:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-net

networks:
  app-net:
    name: fitapet
    external: true
