fitapet:
  domain:
    backend: ${FITAPET_DOMAIN_BACKEND}

---
server:
  address: 0.0.0.0
  port: 8082

spring:
  profiles:
    default: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: full

oauth2:
  client:
    provider:
      kakao:
        jwks-uri: ${KAKAO_JWKS_URI}
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        client-name: Kakao
      google:
        auth-uri: ${GOOGLE_AUTH_URI}
        jwks-uri: ${GOOGLE_JWKS_URI}
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        client-name: Google
      apple:
        jwks-uri: ${APPLE_JWKS_URI}
        client-id: ${APPLE_CLIENT_ID}
        client-secret: ${APPLE_CLIENT_SECRET}
        client-name: Apple

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}
    sms-auth: ${JWT_SECRET_SMS_AUTH}
    sms-oauth: ${JWT_SECRET_SMS_OAUTH}
  token:
    # milliseconds 단위
    access-expiration-time: 1800000 # 30m (30 * 60 * 1000)
    refresh-expiration-time: 604800000 # 7d (7 * 24 * 60 * 60 * 1000)
    sms-auth-expiration-time: 300000 # 5m (5 * 60 * 1000)
    sms-oauth-expiration-time: 300000 # 5m (5 * 60 * 1000)

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
    com.zaxxer.hikari.HikariConfig: DEBUG

ncp:
  api-key: ${NCP_API_ACCESS_KEY}
  secret-key: ${NCP_SECRET_KEY}
  sms:
    service-key: ${NCP_SMS_KEY}
    sender-phone: ${SENDER_PHONE}


---
server:
  port: 8080
  forward-headers-strategy: framework

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

  main:
    allow-bean-definition-overriding: true

  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: full

oauth2:
  client:
    provider:
      kakao:
        jwks-uri: ${KAKAO_JWKS_URI}
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        client-name: Kakao
      google:
        auth-uri: ${GOOGLE_AUTH_URI}
        jwks-uri: ${GOOGLE_JWKS_URI}
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        client-name: Google
      apple:
        jwks-uri: ${APPLE_JWKS_URI}
        client-id: "client-id"
        client-secret: "client-secret"
        client-name: Apple

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}
    sms-auth: ${JWT_SECRET_SMS_AUTH}
    sms-oauth: ${JWT_SECRET_SMS_OAUTH}
  token:
    # milliseconds 단위
    access-expiration-time: 1800000 # 30m (30 * 60 * 1000)
    refresh-expiration-time: 604800000 # 7d (7 * 24 * 60 * 60 * 1000)
    sms-auth-expiration-time: 300000 # 5m (5 * 60 * 1000)
    sms-oauth-expiration-time: 300000 # 5m (5 * 60 * 1000)

ncp:
  api-key: ${NCP_API_ACCESS_KEY}
  secret-key: ${NCP_SECRET_KEY}
  sms:
    service-key: ${NCP_SMS_KEY}
    sender-phone: ${SENDER_PHONE}