fitapet:
  domain:
    backend: ${FITAPET_DOMAIN_BACKEND}

---
server:
  port: 8082

spring:
  profiles:
    default: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: ${NAVER_CLIENT_ID}
#            client-secret: ${NAVER_CLIENT_SECRET}
#            client-name: Naver
#            redirect-uri: "http://localhost:8082/oauth2/callback/naver"
#            authorization-grant-type: authorization_code
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            client-name: Google
#            redirect-uri: "http://localhost:8082/login/oauth2/code/google"
#            authorization-grant-type: authorization_code
#          kakao:
#            client-id: ${KAKAO_CLIENT_ID}
#            client-secret: ${KAKAO_CLIENT_SECRET}
#            client-name: Kakao
#            redirect-uri: "http://localhost:8082/login/oauth2/code/kakao"
#            authorization-grant-type: authorization_code
#          apple:
#            client-id: ${APPLE_CLIENT_ID}
#            client-secret: ${APPLE_CLIENT_SECRET}
#            client-name: Apple
#            redirect-uri: "http://localhost:8082/login/oauth2/code/apple"
#            authorization-grant-type: authorization_code
#        provider:
#            naver:
#                authorization-uri: https://nid.naver.com/oauth2.0/authorize
#                token-uri: https://nid.naver.com/oauth2.0/token
#                user-info-uri: https://openapi.naver.com/v1/nid/me
#                user-name-attribute: response
#            google:
#                authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#                token-uri: https://oauth2.googleapis.com/token
#                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#                user-name-attribute: sub
#            kakao:
#                authorization-uri: https://kauth.kakao.com/oauth/authorize
#                token-uri: https://kauth.kakao.com/oauth/token
#                user-info-uri: https://kapi.kakao.com/v2/user/me
#                user-name-attribute: id
#            apple:
#                authorization-uri: https://appleid.apple.com/auth/authorize
#                token-uri: https://appleid.apple.com/auth/token
#                user-info-uri: https://appleid.apple.com/auth/userinfo
#                user-name-attribute: sub

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  token:
    # milliseconds 단위
    access-expiration-time: 1800000 # 30m (30 * 60 * 1000)
    refresh-expiration-time: 604800000 # 7d (7 * 24 * 60 * 60 * 1000)
    sms-auth-expiration-time: 180000 # 3m (3 * 60 * 1000)

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
    com.zaxxer.hikari.HikariConfig: DEBUG

ncp:
  api-key: ${NCP_API_ACCESS_KEY}
  secret-key: ${NCP_SECRET_KEY}
  sms:
    service-key: ${NCP_SMS_KEY}
    sender-phone: ${SENDER_PHONE}


---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  main:
    allow-bean-definition-overriding: true

  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  token:
    # milliseconds 단위
    access-expiration-time: 1800000 # 30m (30 * 60 * 1000)
    refresh-expiration-time: 604800000 # 7d (7 * 24 * 60 * 60 * 1000)
    sms-auth-expiration-time: 180000 # 3m (3 * 60 * 1000)

ncp:
  api-key: ${NCP_API_ACCESS_KEY}
  secret-key: ${NCP_SECRET_KEY}
  sms:
    service-key: ${NCP_SMS_KEY}
    sender-phone: ${SENDER_PHONE}