name: Continuous Deployment

on:
  push:
    branches: ["develop", "hotfix/86"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - error
      environment:
        description: "Environment"
        required: false
        type: environment

permissions:
  contents: read

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build Gradle
        run: ./gradlew bootJar

      - name: docker image build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_NICKNAME }}/fitapet:latest .
          docker push ${{ secrets.DOCKER_NICKNAME }}/fitapet:latest  
          
      
        
      - name: deploy
        uses: appleboy/ssh-action@0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            ./start.sh